name: 'Call a JS file'
description: 'Call a JS file from a GitHub Action'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  what-to-call:  # id of input
    description: 'What to call'
    required: true
    default: 'HelloWorld'
outputs:
  time: # id of output
    description: 'The time the JS file was called'
runs:
  using: 'node20'
  main: 'dist/index.js'
